export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
export const GET_ANSWERS = "GET_ANSWERS";
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWERS_ERROR = "GET_ANSWERS_ERROR";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
export const DELETE_QUESTIONS_SUCCESS = "DELETE_QUESTIONS_SUCCESS";
export const FETCH_EXISTING_QUESTIONS_SUCCESS =
  "FETCH_EXISTING_QUESTIONS_SUCCESS";
export const FETCH_QUIZ_QUESTIONS_SUCCESS = "FETCH_QUIZ_QUESTIONS_SUCCESS";
